# git clone --recurse-submodules https://github.com/cameronmcnz/surface.git


baseURL: "https://hauki.tech/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Hauki Tech"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Hauki Tech"
  description: "We specialize in cloud infrastructure and application security."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  # social:
  #   dribbble: "#"
  #   instagram: "#"
  #   facebook: "#"
  #   twitter: "#"

  location:
    - "ul. Jana Henryka Dąbrowskiego 77A, Poznan, Poland"

  contact:
    - "corporate@hauki.tech"
    # - "207.555.0119"

  copyright: "© 2023 Hauki Tech All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    # - name: "How we work"
    #   url: "/#"
    #   weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  # buttons:
    # - name: "Book a call"
    #   url: "/#"
    #   weight: 5
    #   pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    # - name: "How we work"
    #   url: "/#"
    #   weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

taxonomies:
  series: "series"
  tags: "tags"
